name: "Terraform"

on:
  push: 
    branches: ["main"]
    paths: ["*.tf", "*.tfvars"]
  workflow_dispatch:

jobs: 
  terraform:
    name: "Terraform Apply"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Configure AWS Credentials" 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: sa-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Terraform Init
        working-directory: ./
        run: terraform init 
        
      - name: Terraform Apply 
        working-directory: ./
        run: terraform apply --auto-approve